# No 1

In [1]:
# Perkalian Matrix
# TTL   : 19 Juni 2005
# No Hp : 082287147039

import numpy as np

A = np.array([[1,9],[0,6],[0,5]])
B = np.array([[1,4],[7,0],[3,9]])

kali = A * B
print(kali)

[[ 1 36]
 [ 0  0]
 [ 0 45]]


# No 2

In [2]:
# Pengurangan Matrix

import numpy as np

A = np.array([[1,9],[0,6],[0,5]])
B = np.array([[1,4],[7,0],[3,9]])

kurang = A - B
print(kurang)

[[ 0  5]
 [-7  6]
 [-3 -4]]


# No 3

In [9]:
# Transpose Matrix

import numpy as np

A = np.array([[1,9],[0,6],[0,5]])
B = np.array([[1,4],[7,0],[3,9]])

transpose_A = np.transpose(A)
transpose_B = np.transpose(B)

print(transpose_A)
print(transpose_B)

[[1 0 0]
 [9 6 5]]
[[1 7 3]
 [4 0 9]]


# No 4

In [22]:
# Nilai Invers

import numpy as np

A = np.array([[1,9],[0,6]])
B = np.array([[1,4],[7,0]])


invers_A = np.linalg.inv(A)
invers_B = np.linalg.inv(B)

print("\nInvers matrix A :")
print("\nInvers matrix B :")
print(invers_A)
print(invers_B)



Invers matrix A :

Invers matrix B :
[[ 1.         -1.5       ]
 [ 0.          0.16666667]]
[[ 0.          0.14285714]
 [ 0.25       -0.03571429]]


# No 5

In [23]:
# Nilai Determinan

import numpy as np

A = np.array([[1,9],[0,6]])
B = np.array([[1,4],[7,0]])

determinant_A = np.linalg.det(A)
determinant_B = np.linalg.det(B)
print("Determinan dari matrix A:", determinant_A)
print("Determinan dari matrix B:", determinant_B)

Determinan dari matrix A: 6.0
Determinan dari matrix B: -27.999999999999996
